apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: app1
  name: app1
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30062
  selector:
    app: nginx
